/**
 * Reads the committed MRT/LRT station catalog generated by
 * `scripts/build-station-catalog.mjs` and exposes code -> name lookups.
 */
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { lineForStationCode, lineMeta } from './railLines.js';
import { formatStopName } from './format.js';

const CATALOG_PATH = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '../data/stations.json',
);

let catalogPromise = null;

export function loadStationCatalog() {
  if (!catalogPromise) {
    catalogPromise = readFile(CATALOG_PATH, 'utf8')
      .then((raw) => JSON.parse(raw))
      .catch(() => ({ generatedAt: null, stationCount: 0, codeCount: 0, lines: {}, byCode: {} }));
  }
  return catalogPromise;
}

/** Official station name for a code, or `null` when the catalog has no entry. */
export async function knownStationName(stationCode) {
  const catalog = await loadStationCatalog();
  const entry = catalog.byCode[String(stationCode || '').toUpperCase()];
  return entry?.name ? formatStopName(entry.name) : null;
}

/**
 * Catalog entry for a station code: `{ name, codes, lines }` where `codes`
 * lists every code of an interchange (e.g. EW24 -> ['EW24', 'NS1']).
 */
export async function stationDetails(stationCode) {
  const catalog = await loadStationCatalog();
  const entry = catalog.byCode[String(stationCode || '').toUpperCase()];
  if (!entry) return null;
  return {
    name: entry.name ? formatStopName(entry.name) : null,
    codes: entry.codes || [],
    lines: entry.lines || [],
  };
}

/** Map of station code -> display name for a whole line (used by the load panel). */
export async function stationNameMap() {
  const catalog = await loadStationCatalog();
  return new Map(
    Object.entries(catalog.byCode || {})
      .filter(([, entry]) => entry.name)
      .map(([code, entry]) => [code, formatStopName(entry.name)]),
  );
}

/** All station codes served by a line, in run order (`NSL` -> ['NS1', 'NS2', ...]). */
export async function lineStationCodes(lineCode) {
  const catalog = await loadStationCatalog();
  const code = String(lineCode || '').toUpperCase();
  const direct = catalog.lines[code]?.stations;
  if (direct?.length) return direct;
  // CGL/CEL branch lines share stations with their parent line.
  const parent = lineMeta(code)?.parent;
  if (parent && catalog.lines[parent]?.stations) {
    return catalog.lines[parent].stations.filter((stationCode) => lineForStationCode(stationCode) === code);
  }
  return [];
}

export async function catalogSummary() {
  const catalog = await loadStationCatalog();
  return {
    generatedAt: catalog.generatedAt,
    stationCount: catalog.stationCount,
    codeCount: catalog.codeCount,
    lines: Object.fromEntries(
      Object.entries(catalog.lines || {}).map(([code, line]) => [code, line.stations.length]),
    ),
  };
}